version: '3'
services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testproject
    ports:
      - 3308:3306
    networks:
      - test_network

  api:
    build:  .
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: testproject
    networks:
      - test_network

networks:
  test_network:
